### ISSUE TITLE
Can not use ClassName::class as table name

### ISSUE THREAD

**Issue by jmgiaever** [somnambulist-tech/cte-builder#2] opened 2021-07-03 09:27 UTC
Hi,

In Doctrine you're able to use mapping to tables. E.g

```
$qb = $this->_em->createQueryBuilder()
    ->select('a')
    ->from(EntityClassName::class, 'a');

$result = $qb->getQuery()->getResult();
```
or alternatively, for an DTO
```
$qb = $this->_em->createQueryBuilder()
    ->select('NEW \App\Entity\DTO\DTOClassName(a.field_1, a.field_n, ..., a.field_n+1')
    ->from(EntityClassName::class, 'a');
```
The result will consist of either EntityClassName-classes (first example) or the DTO class. 

I haven't found a way of doing this with the CTE-builder, but I'm wondering if [the `getSQL` method ](https://github.com/somnambulist-tech/cte-builder/blob/master/src/ExpressionBuilder.php#L217) should call `$this->query->getQuery()->getSQL()` instead of `$this->query->getSQL()` to translate the mapping from `EntityClassName::class` to `table_name`.

....or is there any other way?

Thank you in advance.

**Comment by jmgiaever** [comment] 2021-07-03 09:43
Realized it's QueryBuilder from `DBAL` and not `ORM` that is used, and guess I wont be able to use mapping

**Comment by dave-redfern** [comment] 2021-07-03 16:13
@jmgiaever CTE Builder works with DBAL\QueryBuilder and generates pure SQL. It cannot be used with the ORM query builder. Remember DQL is not SQL and many operations are better done purely in SQL.

If you wanted to get the mapping data for a specific object (e.g. so the table info is entirely dynamic), you could access the EntityManager and get the MetaData class. That could then be fed into the CTE Builders select and wheres etc; but you'd still end up with an SQL query that is executed outside of the ORM (but using the same connection since it's DBAL under-the-hood).

**Comment by dave-redfern** [comment] 2021-07-06 15:32
@jmgiaever I am closing this issue now since it's not a bug. If you do decide to use the CTE Builder and experience other issues or need some help, then please make new issues and tag me so I get notified! I am more than happy to help out.

Thanks 😃

**Closed as completed by dave-redfern** 2021-07-06 15:32 UTC
